AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - files/**/*
    - templates/**/*
    - etc/**/*
    - vendor/**/*

Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Exclude:
    - test/**/*
Metrics/ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - lib/fakefs/file.rb
Naming/MethodName:
  Enabled: false

# TODO: only test ?
Security/Eval:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrivialAccessors:
  ExactNameMatch: true
Style/GuardClause:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
Style/NumericPredicate:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/FrozenStringLiteralComment:
  Enabled: false # TODO: enable
Style/CommentedKeyword:
  Enabled: false # TODO: enable
