language: ruby
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-1.7.27
  - jruby-9.1.17.0
  - jruby-head

env:
  matrix:
    - TASK=test
    - TASK=spec

matrix:
  allow_failures:
    - rvm: jruby-1.7.27
    - rvm: jruby-9.1.17.0
    - rvm: jruby-head
  include:
    - rvm: 2.3.7 # lowest from rvm list above
      env: TASK=rubocop

script: bundle exec rake $TASK
